_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.5
            "6": 4.48.1
            "8":
                - 1
                - 5
            "12": 0.19.5
            "13": linux-x86_64
